version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      # - ./init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./init/postgres-inift.sql:/docker-entrypoint-initdb.d/postgres-init.sql:ro
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRESS_DB}

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - postgres
    # environment:
    #   - MONGO_URI: "mongodb://mongo:27107"
    #   - POSTGRES_URI: ""

volumes:
  mongo_data:
  postgres_data: